services:
    inorder:
        build: .
        ports:
            - "4000:4000"
        depends_on:
            - db
    db:
        image: mysql:latest
        restart: always
        environment:
            - MYSQL_PORT=3306
            - MYSQL_USER=tanmay
            - MYSQL_PASSWORD=pass
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_DATABASE=mvc
        volumes:
            - ./database/migrations:/docker-entrypoint-initdb.d
