services:
    inorder-frontend:
        build:
            context: ./inorder-frontend
            dockerfile: Dockerfile
        image: inorder-frontend:latest
        ports:
            - "5173:3000"
        depends_on:
            - inorder
            - db


    inorder:
        build: .
        image: inorder-backend:latest
        ports:
            - "4000:4000"
        depends_on:
            - db


    db:
        image: mysql:latest
        restart: always

        environment:
            - MYSQL_PORT=3306
            - MYSQL_USER=root
            - MYSQL_PASSWORD=pass
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_DATABASE=mvc
        volumes:
            - ./database/mysql-init/dump.sql:/docker-entrypoint-initdb.d/dump.sql
