MySQL:
    USERNAME: rootmysql
    PASSWORD: pass
    HOST: db:3306
    DATABASE: mvc
    CONN_MAX_LIFETIME: 180
    MAX_OPEN_CONNS: 90
    MAX_IDLE_CONNS: 80
InOrder:
    PORT: 4000
    REFRESH_TOKEN_EXPIRE: 86400
    JTI_CLEANUP_INTERVAL: 1800
    JWT_SECRET: "jwt"
    AUTH_TOKEN_EXPIRY: 3600
    REFRESH_TOKEN_EXPIRY: 3600
    ITEM_IMAGE_DIRECTORY: public/images