USE mvc;

DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS tag_rel CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS refresh_jti CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS items CASCADE;
